=== MoloZzz/Lab2XML/src/main/resources/computer_parts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           targetNamespace="http://example.com"
           xmlns:ex="http://example.com"
           elementFormDefault="qualified"
           xsi:noNamespaceSchemaLocation="computer_parts.xsd">

    <xs:element name="Devices" type="ex:DevicesType"/>

    <xs:complexType name="DevicesType">
        <xs:sequence>
            <xs:element name="Device" maxOccurs="unbounded" type="ex:DeviceType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DeviceType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Origin" type="xs:string"/>
            <xs:element name="Price" type="xs:double"/>
            <xs:element name="Type" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="Critical" type="xs:boolean"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== MoloZzz/Lab2XML/src/main/resources/computer_parts.xml
<?xml version="1.0" encoding="UTF-8"?>
<Devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="computer_parts.xsd">
    <Device id="1">
        <Name>Processor</Name>
        <Origin>USA</Origin>
        <Price>300</Price>
        <Type>Peripheral</Type>
        <Type>EnergyConsumption</Type>
        <Type>Cooler</Type>
        <Critical>true</Critical>
    </Device>
    <Device id="2">
        <Name>Memory</Name>
        <Origin>China</Origin>
        <Price>150</Price>
        <Type>Peripheral</Type>
        <Type>Memory</Type>
        <Critical>false</Critical>
    </Device>
</Devices>
